Add docstrings
thedataincubator/congress-api pull request #15
Opened 2018-09-22 20:54 UTC by johnmarcampbell

Addresses #4 

A few notes:
- I decided on using the [Numpy docstring standard](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard).
- I didn't write any docstrings for the unit tests. Once again following Numpy, I saw that the vast majority of their tests don't use them. I can add some docstrings for the tests if we decide that we want them.
- I tested that these will produce good output when rendering with Sphinx

@thoo or @manonhisway, would one of you mind reviewing this?

2018-09-24 15:18 UTC, thoo commented
@johnmarcampbell 
I am also another current TDI fellow from online cohort. I just reviewed your and it looks great. The only thing I got confused is at `get_all_members(congress, chamber)`. Would that be easier if you mention the type of `chamber` input such as `str` in your docstrings?

2018-09-24 20:18 UTC, thoo commented on congress/congress.py
> +        chamber : {'house', 'senate'}
I think this will be more consistent with the first parameter `congress`. 
```
chamber : str
This can only be 'senate' or 'house'.
```

2018-09-24 20:20 UTC, thoo reviewed
It looks great. My only comment is for `get_all_members` function. I got confused by the type of the second parameters. 
I think this will be more consistent with the first parameter `congress` if you mention the type for `chamber`. 
```
chamber : str
This can only be 'senate' or 'house'.
```

2018-09-25 12:41 UTC, johnmarcampbell commented
@thoo That's a good point. I wrote it this way to conform to the Numpy docstring standard for a [parameter that can only take a fixed set of options](https://numpydoc.readthedocs.io/en/latest/format.html#sections). But I agree that it's not obvious when you're just reading the source code. So I've changed it to `chamber: str {'house', 'senate'}`. I think this is readable, and will look nice when we eventually use Sphinx to turn docstrings into html.

Thanks for the suggestion!

2018-09-25 13:11 UTC, ZachGlassman commented on congress/base.py
> +    validator : validator object
for the parser object you explain what this object does while for the validator you don't.  I would prefer keeping the information about the parser interface in the Parser object.

2018-09-25 13:12 UTC, ZachGlassman commented on congress/base.py
> +        *args : Arguments
maybe say something about how the `*args` are used in building the full query url

2018-09-25 13:12 UTC, ZachGlassman commented on congress/base.py
> +            `get('endpoint', **{'key1':'val1', 'key2':'val2'})`
this is great!

2018-09-25 13:14 UTC, ZachGlassman requested changes
very nice!  only a few suggestions

2018-09-25 15:24 UTC, johnmarcampbell commented on congress/base.py
> +        *args : Arguments
Done.

2018-09-25 15:25 UTC, johnmarcampbell commented on congress/base.py
> +    validator : validator object
Good point. Done.

2018-09-25 15:25 UTC, johnmarcampbell commented on congress/base.py
> +            `get('endpoint', **{'key1':'val1', 'key2':'val2'})`
Thanks :)

2018-09-25 15:30 UTC, johnmarcampbell commented
I've made the requested changes. Thanks for the comments everyone! I don't know if there's a button I need to press somewhere to formally acknowledge that the requested changes have been made?

2018-09-25 22:22 UTC, ZachGlassman commented
Usually you would change the assignment, but usually there are email alerts as well.

2018-09-25 22:23 UTC, ZachGlassman approved these changes

2018-09-25 22:23 UTC, merged